### PR TITLE
Update octodns repo url

### PR DESCRIPTION
**Pull request by xt0rted**
## Description

Updates the  octodns repo url now that it's been moved to its own org.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by solvaholic — APPROVED** [review]
Sweet! Thank you @xt0rted :bow:

**Comment by solvaholic** [comment]
Hm. This is required but isn't running anywhere.

image

**Comment by xt0rted** [comment]
Does this setting have to be checked?

Screenshot_20210213-151440

**Comment by solvaholic** [comment]
I had [removed the `on.pull_request`from the workflow](https://github.com/solvaholic/octodns-sync/commit/69410bb117b6685a8b04fc7d698fc76d17c81de7#diff-ba16fc050e9c818b8125acc6d33b13f4c427ca91373d286af13d0fc92da90605).

To make the linter run I did:

```bash
git fetch origin refs/pull/43/head
git checkout -b pr43 FETCH_HEAD
git push origin pr43
```

Thanks again for this @xt0rted !

**Pull request merged**
